main:
  - identifier: home
    name: Home
    url: /
    weight: 1
  - identifier: blog
    name: Blog
    url: /blog/
    weight: 2
  - identifier: series
    name: Series
    url: /series/
    weight: 3
  - identifier: newsletter
    name: Newsletter
    url: /newsletter/
    weight: 4
  - identifier: about
    name: About
    url: /about/
    weight: 5
  - identifier: search
    name: Search
    url: /search/
    weight: 6
